producer:
  transactionTypeConfigMap:
    debit:
      transactionCountPerSecond: 25
      transactionAmountRange:
        from: -500000
        to: -200
    credit:
      transactionCountPerSecond: 25
      transactionAmountRange:
        from: 200
        to: 500000
  scheduler:
    enabled: true
    initialDelay: 0
    periodInSeconds: 1

audit-system:
  transactionCountThreshold: 1000
  totalValueOfAllTransactionsThreshold: 1000000
  performance:
    batchAuditProcessorAlgorithm: BatchOptimized # [BatchOptimized, TimeOptimized]